CREATE TABLE IF NOT EXISTS task (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT NOT NULL,
    context_id INTEGER NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    due_date TEXT DEFAULT NULL,
    creation_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modification_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS context (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE
);

