CREATE DATABASE IF NOT EXISTS task;

CREATE TABLE IF NOT EXISTS task (
    id SERIAL PRIMARY KEY,
    content VARCHAR(1000) NOT NULL,
    context_id INT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    creation_date VARCHAR(100) NOT NULL,
    modification_date VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS context (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE
);

